[book]
title = "puddingOS"
authors = ["dr-pudding"]
language = "en"
src = "src"

[output.html]
site-url = "https://dr-pudding.github.io/pos"
git-repository-url = "https://github.com/dr-pudding/pos"
edit-url-template = "{path}"
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
additional-css = ["./theme/catppuccin.css", "./theme/extra.css"]
no-section-label = true
